### ISSUE TITLE
need to add support for android 10 above

### ISSUE THREAD

**Issue by nalini690** [TasnuvaOshin/Firebasedatabase_data_to_excel_File_Download_Android#1]
@TasnuvaOshin  code throws error when used in android 10 and above even though after enabling read and write permissions.
error` V/APP: Permission is granted ` then following error shows in logcat
`java.io.FileNotFoundException: /storage/emulated/0/Download/File.xls: open failed: EACCES (Permission denied)`

no gain in request permission

pl. add support for android 10 and above

**Comment by TasnuvaOshin** [comment]
For Android 10 or Above ,Add Run Time Permission (Add Query Permission In your Manifest ) hope this will solve your issue

**Comment by nalini690** [comment]
Hii,Thanks. Working fine now.If you don't mind can I ask another question. This query gives me only the last data in the database. How to get all the data to excel file.
Any help please.

Sent from Yahoo Mail on Android 
 
  On Mon, 28 Mar 2022 at 12:34 pm, Tasnuva Tavasum ***@***.***> wrote:   


For Android 10 or Above ,Add Run Time Permission (Add Query Permission In your Manifest ) hope this will solve your issue
